services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ClearingStreams
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
#    volumes:
#      - "/mnt/d/docker-volumes/ClearingStreams/postgres:/var/lib/postgresql/data"
