create table rule_master
(
    id              bigint generated by default as identity
        primary key,
    post_validation varchar(255),
    priority        integer not null,
    rule            varchar(255),
    type            varchar(255)
);

alter table rule_master
    owner to admin;

