create table rule_amount_limit
(
    id               bigint generated by default as identity
        primary key,
    amount_limit     numeric(38, 2),
    transaction_type varchar(255)
);

alter table rule_amount_limit
    owner to admin;

